BerekeEnergy/Controllers/DictController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BerekeEnergy.Data_Layer;
using BerekeEnergy.Models;

namespace BerekeEnergy.Controllers
{
    public class DictController : Controller
    {
        DataAdapter da = DependencyResolver.Current.GetService<DataAdapter>();

        public ActionResult Index()
        {
            return View();
        }


        public ActionResult Device()
        {
            return View();
        }

        [HttpGet]
        public JsonResult DeviceAjaxHandler()
        {
            var allTypeDevice = da.GetAllDevice();

            return Json(new
            {
                data = allTypeDevice
            }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult DeviceAjaxHandler(DDevaceModel data)
        {
            DDevaceModel result = null;

            if(Request.Params.Get("action") == "create")
            {
                result = da.InsertDevice(data);
            }
            else if(Request.Params.Get("action") == "edit")
            {
                result = da.UpdateDevice(data);
            }
            else if(Request.Params.Get("action") == "remove")
            {
                da.DeleteDevice(data);
                result = data;
            }

            return Json(new
            {
                data = result
            }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult TypeDevice()
        {
            return View();
        }

        [HttpGet]
        public JsonResult TypeDeviceAjaxHandler()
        {
            var allTypeDevice = da.GetAllTypeDevice();

            return Json(new
            {
                data = allTypeDevice
            }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult TypeDeviceAjaxHandler(DTypeDeviceModel data)
        {
            DTypeDeviceModel result = null;

            if(Request.Params.Get("action") == "create")
            {
                result = da.InsertTypeDevice(data);
            }
            else if(Request.Params.Get("action") == "edit")
            {
                result = da.UpdateTypeDevice(data);
            }
            else if(Request.Params.Get("action") == "remove")
            {
                da.DeleteTypeDevice(data);
                result = data;
            }

            return Json(new
            {
                data = result
            }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult Tariff()
        {
            return View();
        }

        [HttpGet]
        public JsonResult TariffAjaxHandler()
        {
            var allTariff = da.GetAllTariff();

            return Json(new
            {
                data = allTariff
            }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult TariffAjaxHandler(DTariffModel data)
        {
            DTariffModel result = null;

            if(Request.Params.Get("action") == "create")
            {
                result = da.InsertTariff(data);
            }
            else if(Request.Params.Get("action") == "edit")
            {
                result = da.UpdateTariff(data);
            }
            else if(Request.Params.Get("action") == "remove")
            {
                da.DeleteTariff(data);
                result = data;
            }

            return Json(new
            {
                data = result
            }, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public JsonResult GetTypeDeviceAjaxHandler()
        {
            var allTypeDevice = da.GetAllTypeDeviceForList();

            var a = (from b in allTypeDevice
                     select new 
                     { 
                     b.label,
                     b.value
                     }).ToArray();

            return Json(a, JsonRequestBehavior.AllowGet);
        }
        [HttpGet]
        public JsonResult GetTariffAjaxHandler()
        {
            var allTypeDevice = da.GetAllTariffForList();

            var a = (from b in allTypeDevice
                     select new
                     {
                         b.label,
                         b.value
                     }).ToArray();

            return Json(a, JsonRequestBehavior.AllowGet);
        }
    }
}

BerekeEnergy/Controllers/GeneralIndicationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;
using BerekeEnergy.Data_Layer;
using BerekeEnergy.Models;

namespace BerekeEnergy.Controllers
{
    public class GeneralIndicationController : Controller
    {
        DataAdapter da = DependencyResolver.Current.GetService<DataAdapter>();

        // GET: GeneralIndication
        public ActionResult GeneralIndex()
        {
            return View();
        }

        // GET: GeneralIndication/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: GeneralIndication/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: GeneralIndication/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: GeneralIndication/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: GeneralIndication/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: GeneralIndication/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: GeneralIndication/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        public JsonResult GenIndAjaxHandler(jQueryDataTableParamModel param)
        {
            var allCompanies = da.GetAllTypeDevice();

            var result = from c in allCompanies
                         select new DTypeDeviceModel { 
                
                    Id = c.Id, 
                    code = c.code, 
                    name = c.name
            };

            return Json(new
            {
                data = result
            }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult GenIndAjaxHandler2(DTypeDeviceModel data)
        {
            var allCompanies = da.GetAllTypeDevice();

            var result = from c in allCompanies
                         select new DTypeDeviceModel
                         {

                             Id = c.Id,
                             code = c.code,
                             name = c.name
                         };

            return Json(new
            {
                data = result
            }, JsonRequestBehavior.AllowGet);
        }
    }
}

BerekeEnergy/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/dataTables")
    @Scripts.Render("~/bundles/_BerekeEnergy")
    

    <script type="text/javascript">
        var appInsights = window.appInsights || function (config) {
            function s(config) { t[config] = function () { var i = arguments; t.queue.push(function () { t[config].apply(t, i) }) } } var t = { config: config }, r = document, f = window, e = "script", o = r.createElement(e), i, u; for (o.src = config.url || "//az416426.vo.msecnd.net/scripts/a/ai.0.js", r.getElementsByTagName(e)[0].parentNode.appendChild(o), t.cookie = r.cookie, t.queue = [], i = ["Event", "Exception", "Metric", "PageView", "Trace"]; i.length;) s("track" + i.pop()); return config.disableExceptionTracking || (i = "onerror", s("_" + i), u = f[i], f[i] = function (config, r, f, e, o) { var s = u && u(config, r, f, e, o); return s !== !0 && t["_" + i](config, r, f, e, o), s }), t
        }({
            instrumentationKey: "e61fd2f6-c209-41d7-bd75-e9de7a0832d9"
        });

        window.appInsights = appInsights;
        appInsights.trackPageView();
    </script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    <li>@Html.ActionLink("Головной счетчик", "GeneralIndex", "GeneralIndication")</li>
                    <li>@Html.ActionLink("Справочник", "Index", "Dict")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @RenderSection("scripts", required: false)
</body>
</html>